src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $ordre = null;

    #[ORM\Column(nullable: false)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?Prestataire $images_Logo = null;

    #[ORM\ManyToOne(inversedBy: 'images_photo')]
    private ?Prestataire $images_photo = null;

    #[ORM\OneToOne(mappedBy: 'image', cascade: ['persist', 'remove'])]
    private ?CategorieService $categorieService = null;

    #[ORM\OneToOne(inversedBy: 'image', cascade: ['persist', 'remove'])]
    private ?Internaute $image_internaute = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(?int $ordre): self
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImagesLogo(): ?Prestataire
    {
        return $this->images_Logo;
    }

    public function setImagesLogo(?Prestataire $images_Logo): self
    {
        $this->images_Logo = $images_Logo;

        return $this;
    }

    public function getImagesPhoto(): ?Prestataire
    {
        return $this->images_photo;
    }

    public function setImagesPhoto(?Prestataire $images_photo): self
    {
        $this->images_photo = $images_photo;

        return $this;
    }

    public function getCategorieService(): ?CategorieService
    {
        return $this->categorieService;
    }

    public function setCategorieService(?CategorieService $categorieService): self
    {
        // unset the owning side of the relation if necessary
        if ($categorieService === null && $this->categorieService !== null) {
            $this->categorieService->setImage(null);
        }

        // set the owning side of the relation if necessary
        if ($categorieService !== null && $categorieService->getImage() !== $this) {
            $categorieService->setImage($this);
        }

        $this->categorieService = $categorieService;

        return $this;
    }

    public function getImageInternaute(): ?Internaute
    {
        return $this->image_internaute;
    }

    public function setImageInternaute(?Internaute $image_internaute): self
    {
        $this->image_internaute = $image_internaute;

        return $this;
    }

    public function __toString()
    {
        return $this->image;
    }

}

src/Controller/PartenaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Prestataire;
use App\Form\CommentaireType;
use OpenCage\Geocoder\Geocoder;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PartenaireController extends AbstractController
{

    // ----------------------------------------------------------------
    // Affichage de tous les Prestataires (+ pagination)
    // ----------------------------------------------------------------
    /**
     * @Route("/partenaires",name="listePartenaires")
     */
    public function listePrestataires(EntityManagerInterface $entityManager, Request $request, PaginatorInterface $paginator): Response
    {

        $repository = $entityManager->getRepository(Prestataire::class);
        $partenaires = $repository->findAll();

        // Utilise le bundle de pagination => https://github.com/KnpLabs/KnpPaginatorBundle
        $pagination = $paginator->paginate(
            $partenaires, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            5 // Définition de la limite d'items par page
        );

        return $this->render('partenaire/liste.html.twig', [
            'partenaires' => $partenaires,
            'pagination' => $pagination
        ]);
    }

    // ----------------------------------------------------------------
    // Affichage detail d'un Prestataire + commentaire (si authentifié en tant qu'User)
    // ----------------------------------------------------------------
    /**
     * @Route("partenaires/detail/{id}", name="detailPartenaire")
     */

     // userInterface permet de récupérer l'utilisateur actuellemnt authentifié
    public function detailPrestataire($id, EntityManagerInterface $entityManager, Request $request, PaginatorInterface $paginator)
    {

      $repository = $entityManager->getRepository(Prestataire::class);
      $partenaire = $repository->find($id);

      $rue = $partenaire->getUtilisateur()->getAdresseRue();
      $num = $partenaire->getUtilisateur()->getAdresseNum();
      $commune= $partenaire->getUtilisateur()->getCommune()->getCommune();
      $codePostal= $partenaire->getUtilisateur()->getCodePostal()->getCodePostal();
      $adresse= ($rue." ".$num." ".$codePostal." ".$commune);

        // Appel de l'API Geocoder (opencagedata.com) pour récupérer les coordonnées GPS de l'adresse du Prestataire
        $geocoder = new Geocoder('b091b28cf9ff4f33acbedc0c90166f8c');// <- Entrez ici votre clé API

        $result = $geocoder->geocode($adresse);
        if($result){
            // récupération des données de latitude et longitude de l'adresse passée en paramêtre
            if(isset($result['results'][0]['geometry']['lat']) && isset($result['results'][0]['geometry']['lng'])){
                $lat = $result['results'][0]['geometry']['lat'];
                $lng = $result['results'][0]['geometry']['lng'];
            }else{
            $lat = null;
            $lng = null;
        }
    }


        $commentaire = new Commentaire;
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $form = $form->getData();
            $commentaire->setTitre($form->getTitre());
            $commentaire->setContenu($form->getContenu());
            $commentaire->setDateEncodage(new \DateTime);
            $commentaire->setPrestataire($partenaire);
            $utilisateur = $partenaire->getUtilisateur();
            $commentaire->setInternaute($utilisateur->getInternautes());


            $entityManager->persist($commentaire);
            $entityManager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été envoyé');


            return $this->redirectToRoute('detailPartenaire',  [
                'id' => $partenaire->getId(),
            ]);
        }


        return $this->render('partenaire/detail.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
            "lat" => $lat,
            "lng" => $lng,
        ]);
    }

}

templates/partenaire/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{partenaire.nom}}
{% endblock %}

{% block titreh1 %}
    {{partenaire.nom}}
{% endblock %}

{% block searchForm %}
	{% embed "_searchFormToggle.html.twig" %}{% endembed %}
{% endblock %}

{% block body %}
  <article>
    <div class="partenaire-avatar">
      {% if partenaire.images[0] is defined and partenaire.images[0] != '' %}
        <img class="prestaire_img" src="{{ asset('images/uploads/' ~ partenaire.images[0]) }}" alt="photo de profil du prestataire"/>
      {% else %}
        <img class="prestaire_img" src="{{ asset('images/avatars/blank_profile.webp') }}" alt="photo de profil du prestataire"/>
      {% endif %}
    </div>

    {# Les promotions ne sont visibles que par les utilisateurs identitfiés #}
    {% if is_granted("ROLE_USER") and not is_granted('ROLE_PREST') %}
        {% for pr in partenaire.promotion %}
         {% if date(pr.affichageDe) < date() and date(pr.affichageJusque) > date() %}
          <div class="prestataire-detail-promotion">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#a1d2d0" fill-opacity="1" d="M0,288L40,245.3C80,203,160,117,240,106.7C320,96,400,160,480,170.7C560,181,640,139,720,149.3C800,160,880,224,960,213.3C1040,203,1120,117,1200,90.7C1280,64,1360,96,1400,112L1440,128L1440,0L1400,0C1360,0,1280,0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z"></path></svg>
            <h4>{{ pr.nom }}</h4>
            <p>Du: {{pr.debut|date("d/m/Y") }} au: {{pr.fin|date("d/m/Y")}}</p>
            <p>Dans la catégorie <span>{{pr.categorieService}}</span></p>
            <p class="prestataire-detail-promotion-description">{{ pr.description }}</p>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#a1d2d0" fill-opacity="1" d="M0,288L40,245.3C80,203,160,117,240,106.7C320,96,400,160,480,170.7C560,181,640,139,720,149.3C800,160,880,224,960,213.3C1040,203,1120,117,1200,90.7C1280,64,1360,96,1400,112L1440,128L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path></svg>
          </div>
        ! {% endif %}
      {% endfor %}
    {% endif %}
    {% if partenaire.proposer is not empty %}
    <div class="prestataire-detail">
      <h3 class="prestataire-detail-list-title">Mes catégories de service</h3>
      <div class="prestataire-detail-list">
        <ul>
          {% for service in partenaire.proposer %}
          <li>
            <a href="{{path('detailService',{id : service.id} )}}">{{ service.nom}}</a>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% else %}
      <div class="prestataire-detail-list">
        <p class="prestataire-detail-no-data">Je ne propose pas encore de catégorie de service</p>
      </div>
    {% endif %}
    {% if partenaire.stage is not empty %}
    <div class="prestataire-detail">
      <h3 class="prestataire-detail-list-title">Les stages que je propose actuellement</h3>
      <div class="prestataire-detail-list">
        <ul>
            {% for st in partenaire.stage %}
              {# test si le stage est dans sa periode d'affichage. Si oui -> Affichage #}
              {% if date(st.affichageDe) < date() and date(st.affichageJusque) > date() %}
                <li>
                  <a href="{{path('detailStage',{id : st.id} )}}">{{st.nom}}</a>
                </li>
              {% endif %}
            {% endfor %}
        </ul>
      </div>
    </div>
    {% else %}
      <p class="prestataire-detail-no-data">Je ne propose pas de stage pour le moment</p>
   {% endif %}

    {# Carrousel photos prestataire #}
    <div class="gallery">
    {% if partenaire.imagesPhoto is not empty %}
        {% for img in partenaire.imagesPhoto %}
          <img class="prestaire_img" src="{{ asset('images/uploads/' ~ img) }}" alt="photo carrousel"/>
        {% endfor %}
        {% else %}
        <p class="prestataire-detail-no-data">😱 Oops je ne propose pas encore de photo dans ma gallerie...</p>
    {% endif %}
    </div>

    <div class="prestataire-detail">
      <h3 class="prestataire-detail-contact-title">Mes informations</h3>
      <ul>
      <li>
        <div class="mailto-prest">
          <a href="mailto:{{ partenaire.utilisateur}}">Me contacter par Email</a>
        </div>
      </li>
      <li>
          <span>Mon site web: </span><a href="#">{{ partenaire.siteWeb }}</a>
        </li>
        <li>
          <span>Tél: </span>{{ partenaire.tel }}
        </li>
        <li>
          <span>N° TVA: </span>{{ partenaire.tvaNum }}
        </li>
      </ul>
    </div>

    <div class="prestataire-detail">
      <h3 class="prestataire-detail-adress-title">Où me trouver: </h3>
      {% if partenaire.utilisateur.adresseRue is defined and  partenaire.utilisateur.adresseNum is defined and partenaire.utilisateur.codePostal is defined and partenaire.utilisateur.commune is defined%}
        <p>{{ partenaire.utilisateur.adresseRue }} {{ partenaire.utilisateur.adresseNum }}</p>
        <p>{{ partenaire.utilisateur.codePostal }} {{ partenaire.utilisateur.commune }}</p>
        
        {# Map leaftlet ************************************ #}
        {# Récupération de la longitude et latitude dans le js -> js/map.js #}
        <p style="display: none" id="map-lat">{{lat}}</p>
        <p style="display:none" id="map-lng">{{lng}}</p>

        <div id="map"></div>


      {% else %}
       <p class="prestataire-detail-no-data">Oops, je n'ai pas encore renseigné mon adresse</p>
      {% endif %}
    </div>
    
    {% if is_granted('ROLE_USER') and not is_granted('ROLE_PREST') %}
    <div class="prestataire-detail-add-comment-form">
      <h3 class="prestataire-detail-add-comment-form-title">Ajouter un commentaire</h3>
      {{ form_start(form) }}
      <div class="prestataire-detail-add-comment-form-row">
        {{ form_label(form.titre) }}
        {{ form_widget(form.titre) }}
      </div>
      <div class="prestataire-detail-add-comment-form-row">
        {{ form_label(form.contenu) }}
        {{ form_widget(form.contenu) }}
      </div>
      <div class="prestataire-detail-add-comment-form-submit">
        {{ form_widget(form.commenter) }}
      </div>
      {{ form_end(form) }}
    </div>
    {% endif %}

    <div class="prestataire-detail">
       <h3 class="prestataire-detail-list-title">Commentaires</h3>
      {% for com in partenaire.commentaires %}
        <div class="prestataire-detail-comments">
          <h4>{{com.titre}}</h4>
          <p class="prestataire-detail-comments-content">{{com.contenu}}</p>
          <div class="prestataire-detail-comments-date-author">
            <p>Le {{com.dateEncodage| date('d/m/Y')}}</p>
            {% if app.user.internautes.prenom is defined %}
                 <p> par: {{app.user.internautes.prenom }}</p>
                 {% else %}
                 <p> par: Anonyme</p>
            {% endif %}
          </div>
        </div>
        <div class="prestataire-detail-comments-separator"></div>
      {% endfor %}
    </div>
  </article>

{% endblock %}

templates/partenaire/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos partenaires
{% endblock %}

{% block titreh1 %}
	<h1>Prestataires</h1>
{% endblock %}

{% block searchForm %}
	{% embed "_searchFormToggle.html.twig" %}{% endembed %}
{% endblock %}

{% block body %}
<div class="countPrestataireFound">
    {{ pagination.getTotalItemCount }} prestataire(s) trouvé(s)
</div>
	{% if app.user and app.user.roles[0] == 'ROLE_USER' %}
		<div class="register-as-prestataire-link">
			<a href="{{path ("prestataire_register", {id: app.user.id})}}">M'inscrire en tant que prestataire</a>
		</div>
	{% endif %}
	{% if partenaires %}
		<div class="partenaires-list-wrap">
			{% for partenaire in pagination %} 
				<a class="partenaires-card" href="{{path('detailPartenaire',{id : partenaire.id})}}">
					{% if partenaire.images[0] is defined and partenaire.images[0] != '' %}
						<img class="prestataire_img" src="{{ asset('images/uploads/' ~ partenaire.images[0]) }}" alt="photo de profil du prestataire"/>
					{% else %}
						<img class="prestataire_img" src="{{ asset('images/avatars/blank_profile.webp') }}" alt="photo de profil du prestataire"/>
					{% endif %}
					{% if partenaire.nom is defined %}
						<div>
							<h3>{{partenaire.nom}}</h3>
						</div class="partenaires-card-name">
					{% endif %}
				</a>
			{% endfor %}
		</div>
		{% else %}
			<div class="aucun-resultat-prestataire">
				<p>Désolé, il n'y a aucun prestataire correspondant à votre recherche</p>
			</div>
	{% endif %}

	{# display navigation #}
	<div class='l-main-pagination'>
		<div class="navigation">
			{{ knp_pagination_render(pagination) }}
		</div>
	</div>
{% endblock %}